// <auto-generated />
using System;
using Dal.DataBaseHelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dal.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20190406174249_firstMigration1")]
    partial class firstMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dal.Model.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<long?>("PlayerGuessingNumberId");

                    b.Property<long>("PlayerMakeNumberId");

                    b.HasKey("Id");

                    b.HasIndex("PlayerGuessingNumberId");

                    b.HasIndex("PlayerMakeNumberId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Dal.Model.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Dal.Model.Statistic", b =>
                {
                    b.Property<long>("Id");

                    b.Property<int>("LoseCount");

                    b.Property<int>("Score");

                    b.Property<int>("WinCount");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Dal.Model.Game", b =>
                {
                    b.HasOne("Dal.Model.Player", "PlayerGuessingNumber")
                        .WithMany("Games")
                        .HasForeignKey("PlayerGuessingNumberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dal.Model.Player", "PlayerMakeNumber")
                        .WithMany()
                        .HasForeignKey("PlayerMakeNumberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dal.Model.Statistic", b =>
                {
                    b.HasOne("Dal.Model.Player", "Player")
                        .WithOne("Statistic")
                        .HasForeignKey("Dal.Model.Statistic", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
